# 🐳 Docker Compose for Bakery MERN System
# Quick deployment configuration for same server hosting

version: "3.8"

services:
  # Backend Service
  bakery-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bakery-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=shinkansen.proxy.rlwy.net
      - DB_PORT=24785
      - DB_NAME=railway
      - DB_USER=root
      - DB_PASSWORD=ZEsGFfzwlnsvgvcUiNsvGraAKFnuVZRA
      - GEMINI_API_KEY=AIzaSyD813Gu6WszqsjbEq-5MvO5GYlxj5By8fE
      - GEMINI_MODEL=gemini-1.5-pro-latest
      - CORS_ORIGIN=http://localhost:3000,http://localhost:80
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - bakery-network

  # Frontend Service
  bakery-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bakery-frontend
    ports:
      - "3000:80"
    depends_on:
      - bakery-backend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:5000
    restart: unless-stopped
    networks:
      - bakery-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: bakery-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl # SSL certificates if available
    depends_on:
      - bakery-backend
      - bakery-frontend
    restart: unless-stopped
    networks:
      - bakery-network

networks:
  bakery-network:
    driver: bridge

volumes:
  bakery_logs:
  bakery_uploads:
